name: class213565

on:
  schedule:
    - cron: '0 5 6 * * 5 *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Push Information
      run: |
        python push.py class213 14:30大学生心理健康 和梦雪
    