name: class2145512

on:
  workflow_dispatch:
  schedule:
    - cron: '55 1 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Push Information
      env:
        token: ${{ secrets.token }}
      run: |
        python push.py class214 10:20大学英语（1） 闫晓慧
    